### ISSUE TITLE
Script repository is the same as Magerun 1

### ISSUE THREAD

**Issue by JBleijenberg** [netz98/n98-magerun2#235]
Hi,

The script repository (/usr/local/share/n98-magerun/scripts or ~/.n98-magerun) is the same
as Magerun 1.
This is an issue when you have M1 and M2 installed on the same server, but want the scripts to be seperated (we don't use the same scripts for M1 and M2).

Can you change the script repository to make it unique for Magerun 2, or add a 3rd directory for Magerun 2.

**Comment by ktomk** [comment]
I just pushed some related changes to the development branch. Can you please update to unstable and test if it works for you now?

~~~
n98-magerun2.phar self-update --unstable
~~~

**Comment by JBleijenberg** [comment]
@ktomk unfortunately it still searches in the magerun directories (instead of e.g magerun2):
```
 Simply place a script in folder */usr/local/share/n98-magerun/scripts* or in your home dir
 in folder *<HOME>/.n98-magerun/scripts*.
```
Atleast, that's what ```---help``` tells me. 
I'd love to see magerun2 look for scripts in ```/usr/local/share/n98-magerun2/scripts``` and ```<HOME>/.n98-magerun2/scripts```, to keep things seperated.

**Comment by JBleijenberg** [comment]
Better yet, when the scripts directory is not present, the following error occurs when calling ```n98-magerun2 script:repo:list```:
```
  [LogicException]
  You must call one of in() or append() methods before iterating over a Finder.
```

**Comment by ktomk** [comment]
I've not yet updated the help, but good point. Touched it and also checked for the exception case. Please update and try against unstable again.

**Comment by ktomk** [comment]
We believe that the bug reported is fixed in the development version. It can be upgraded to it using the `self-update` command with the `--unstable` switch.

**Comment by tkn98** [comment]
@JBleijenberg: Can you provide feedback if this worked well for you? Would be good to know before pushing the next stable release.

**Comment by JBleijenberg** [comment]
@tkn98 it partially works.
It now finds my scripts in `~/.n98-magerun2/scripts`. However, it doesn't find them when i place my scripts in `/usr/local/share/n98-magerun2/scripts`

**Comment by tkn98** [comment]
@JBleijenberg: I'll review this. And no more mix-ups for `/usr/local/share/n98-magerun*`, e.g. still showing Magerun 1 scripts in Magerun 2 for that `/usr/local` folder?

**Comment by JBleijenberg** [comment]
@tkn98 yeah, when i place my scripts in the `/usr/local/share/n98-magerun/` directory, magerun2 still picks them up

**Comment by ktomk** [comment]
@JBleijenberg: Thanks for the clarification. A change in the configuration file was still missing. That local folder was hard-encoded.

We believe that the bug reported is fixed in the development version. It can be upgraded to it using the `self-update` command with the `--unstable` switch.

Please give it a try it should now work as expected for you.
