### ISSUE TITLE
Run composer with the same interpreter as magerun2

### ISSUE THREAD

**Issue by shochdoerfer** [netz98/n98-magerun2#295]
I have PHP 5.6, PHP 7.0 and PHP 7.1 installed on my host. Recently I made PHP 7.1. the default PHP interpreter.

Now when trying to install a new Magento project via magerun2 by simply running `magerun2 install`.
Composer fails as magento/product-community-edition requires php ~5.6.5|7.0.2|7.0.4|~7.0.6. I tried to "solve" the problem by running magerun2 via `php7.0 /usr/local/bin/magerun2 install`. The outcome was the same.

I could see 2 workarounds for this:
- Composer could be invoked with the --ignore-platform-reqs flag
- Magerun2 could invoke Composer with the same PHP interpreter as Magerun2 was invoked with

I am not really a fan of the --ignore-platform-reqs flag, thus I would prefer the 2nd solution. Is there any real need for this? If so, I'd love to hack on this little feature.

**Comment by cmuench** [comment]
Thanks for reporting. I prefer to version 2. It is not a workaround for me.

**Comment by shochdoerfer** [comment]
Cool. I try to tackle the issue then. Will send a PR when I am done.

**Comment by cmuench** [comment]
@shochdoerfer 👍

**Comment by ktomk** [comment]
The install command should have a command-line switch for that to remain backwards compatible.

There then could be another easy switch to default to PHP_BINARY (this should be found in src in some different (?) cmds already, we couldn't do it that easily in Magerun 1 due to PHP version constraints).

IIRC there is also an existing command-line switch for further composer parameters, the new switch could/should be aligned with these names (if not yet already possible via CLI).

Additionally one could also see how this was solved in Composer itself which has some similar functionality which allows to execute PHP scripts with the same interpreter: https://github.com/composer/composer/commit/b0000617cc7bc481d839eb3c59d81bbcbaef34a4 .

(technically ignore platform reqs is correct for composer calls in that situation, we've done that at N98 and it works exactly for that. It also makes clear that the user knows actually what she's doing. It's also perhaps worth to say that Magento 2 install via composer directly works well, the install command is perhaps a bit aged in Magerun 2, just my 2 cents)

(unfortunately, https://github.com/composer/composer/issues/4931 is unimplemented)

**Comment by shochdoerfer** [comment]
Using PHP_BINARY is how I started to solve the problem, also had to fix a few side-effects like finding the absolute path to composer. Working fine on Linux so far, need to test it on Windows. Since you pointed out the Composer feature, does it make sense to add another dependency like symfony/process to handle the PHP_BINARY lookup or should I implement the logic myself?

Is it really needed to have the command-line switch to remain backwards compatible?

As for the --ignore-platform-reqs flag this might indeed be interesting, but probably a separate PR. What do you think?

**Comment by ktomk** [comment]
In Magerun2 there is no need for PHP 5.3 or Windows support.

I think to keep things simple is to add a new command-line option with an argument specifying the composer command. default value should be current composer command (the binary) for the `install` command.

Then another command-line option (which would not require an argument) that makes the install command to use PHP binary of the Magerun utility itself and resolve the composer path. For that I would suggest to add another utility function next to https://github.com/netz98/n98-magerun2/blob/develop/src/N98/Util/OperatingSystem.php#L70 , that utility class so far wraps this logic in Magerun and it looks like you will have a subroutine here.

If you still want to play with Windows support, there is another related utility class [**WindowsSystem**](https://github.com/netz98/n98-magerun2/blob/develop/src/N98/Util/WindowsSystem.php) which we keep aligned with Magerun 1 sources. It already contains resolution of executables for Windows, it could have had a similar subroutine then. Keep in mind that we don't have a Windows build yet, so this requires manual testing on a Windows system. For starters I'd say it's better to ignore Windows unless you really need this yourself.

**Comment by shochdoerfer** [comment]
Minor update: Still have this on my mind. Just could not find the time to finalize the PR. Crossing fingers that it will happen in 2018 :)
